name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: TypeScript validation
        working-directory: ./frontend
        run: npx tsc --noEmit
      - name: Build
        working-directory: ./frontend
        run: npm run build

  tests:
    name: Run Pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ha-version: ["2024.11.0", "latest"]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"
      - name: Set up uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv pip install --system -r requirements-dev.txt zeep
          if [ "${{ matrix.ha-version }}" != "latest" ]; then
            uv pip install --system homeassistant==${{ matrix.ha-version }}
          fi
      - name: Run tests and coverage
        run: |
          PYTHONPATH=. coverage run -m pytest tests/
          coverage report --fail-under=90
